schema=1
os_id=rhel
arch=x86_64
scheduler=pbspro
scheduler_commands=qsub,qstat,qdel
module_commands=modulecmd
environment_commands=none
container_commands=singularity,podman
debugger_commands=gdb,strace,cuda-gdb
profiler_commands=valgrind,nsys,ncu
