schema=1
os_id=rhel
arch=x86_64
scheduler=pbspro
command_paths=/opt/pbs/bin,/home/apps/pbs_wrapper/bin
scheduler_commands=qsub,qstat,qdel
module_commands=modulecmd
environment_commands=none
container_commands=singularity,podman
debugger_commands=gdb,strace,cuda-gdb
profiler_commands=valgrind,nsys,ncu
persistent_root=/groups/gag51395/yokota
cache_root=/groups/gag51395/yokota/cache
