schema=1
os_id=sles
arch=aarch64
scheduler=slurm
command_paths=none
scheduler_commands=sbatch,srun,squeue,scancel
module_commands=ml
environment_commands=uenv
container_commands=docker,podman
debugger_commands=gdb,strace
profiler_commands=perf
persistent_root=/capstor/store/cscs/director2/g177/ryokota
cache_root=/capstor/scratch/cscs/ryokota/home-cache
