schema=1
os_id=ubuntu
arch=x86_64
scheduler=yrun
command_paths=none
scheduler_commands=yrun,ybatch
module_commands=modulecmd
environment_commands=none
container_commands=docker,podman
debugger_commands=gdb,strace,cuda-gdb
profiler_commands=valgrind,perf,nsys,ncu
persistent_root=/mnt/nfs-03/safe/Users/rioyokota
cache_root=/mnt/nfs-03/fast/Users/rioyokota/home-cache
