schema=1
os_id=ubuntu
arch=x86_64
scheduler=yrun
command_paths=/mnt/nfs/packages-24.04/x86_64/yokota-rns/bin,/mnt/nfs/packages/x86_64/cuda/cuda-12.8/bin
scheduler_commands=yrun,ybatch
module_commands=modulecmd
environment_commands=none
container_commands=docker,podman
debugger_commands=gdb,strace,cuda-gdb
profiler_commands=valgrind,perf,nsys,ncu
persistent_root=/mnt/nfs-03/safe/Users/rioyokota
cache_root=/mnt/nfs-03/fast/Users/rioyokota/home-cache
