schema=1
os_id=rocky
arch=x86_64
scheduler=slurm
command_paths=none
scheduler_commands=sbatch,srun,squeue,scancel
module_commands=modulecmd
environment_commands=none
container_commands=singularity,podman
debugger_commands=gdb,strace
profiler_commands=valgrind
persistent_root=/lvs0/rccs-asfm/rio.yokota
cache_root=/lvs0/rccs-asfm/rio.yokota/cache
