schema=1
os_id=ubuntu
arch=aarch64
scheduler=slurm
command_paths=none
scheduler_commands=sbatch,srun,squeue,scancel
module_commands=none
environment_commands=none
container_commands=singularity,apptainer
debugger_commands=gdb,strace
profiler_commands=valgrind
persistent_root=/data1/rkp00015/rku00075
cache_root=/data1/rkp00015/rku00075/cache
