schema=1
os_id=rhel
arch=x86_64
scheduler=age
command_paths=/apps/t4/rhel9/uge/latest/bin/lx-amd64
scheduler_commands=qsub,qstat,qdel
module_commands=modulecmd
environment_commands=none
container_commands=apptainer
debugger_commands=gdb,strace,cuda-gdb
profiler_commands=valgrind,nsys,ncu
persistent_root=/gs/bs/jh250019/yokota
cache_root=/gs/fs/jh250019/yokota/home-cache
