Host github
	ForwardX11 no
	HostName github.com
	User git
# Defaults

Host *
	AddKeysToAgent yes
	ForwardAgent yes
	ForwardX11 yes
	ForwardX11Trusted yes
	ServerAliveInterval 15
	ControlMaster auto
	ControlPath ~/.ssh/cm-%r@%h-%p
	ControlPersist yes
	#XauthLocation /opt/X11/bin/xauth
