#!/usr/bin/env python3
"""Apply the exact public startup simplifications reviewed in T-249."""

from __future__ import print_function

import argparse
import base64
import datetime
import json
import os
import re
import stat
import subprocess
import sys
import tempfile


ROOT = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
HOSTS = ("local", "ab", "ab2", "ri", "al", "rc", "t4")
SSH_FORWARD_HOSTS = ("ab", "ab2", "al", "rc", "ri", "t4")


class Refusal(Exception):
    pass


def b(value):
    return value.encode("utf-8")


def rule(name, before, after):
    return {"name": name, "before": b(before), "after": b(after)}


MANAGED_LOCAL = """# >>> harness managed >>>
HARNESS_LOGICAL_HOST=local
export HARNESS_LOGICAL_HOST
if [ -r "$HOME/harness/shell/profile.sh" ]; then
    . "$HOME/harness/shell/profile.sh"
fi
# <<< harness managed <<<
"""


def module_hook(host):
    return """# Default module stack
if [ -r "$HOME/harness/shell/module-stack.sh" ]; then
    . "$HOME/harness/shell/module-stack.sh" %s
fi
""" % host


LOCAL_RULES = [
    rule("local-alias-prefix", """# Aliases
alias a='./a.out'
""", """# Local-only alias
"""),
    rule("local-common-policy", """alias ducks='du -cks * | sort -rn | head -11'
alias grep='grep --binary-files=without-match --color=auto'
alias la='ls -ah'
alias ll='ls -hl'
alias lla='ls -ahl'
alias ls='ls --color=auto'
alias v='vim'

# Default editor
export EDITOR='vim'
# Unlimited bash history in .bash_history
export HISTFILESIZE=
# Unlimited bash history in memory
export HISTSIZE=

# Prompt
PS1='\\u@\\h:\\W\\$ '

# Set global install path
export FS=$HOME

# Local installs
export PATH=$FS/.local/bin:$PATH
export CPATH=$FS/.local/include:$CPATH
export LIBRARY_PATH=$FS/.local/lib:$LIBRARY_PATH
export LD_LIBRARY_PATH=$FS/.local/lib:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$FS/.local/lib/pkgconfig

# >>> harness managed >>>
""", """
# >>> harness managed >>>
"""),
]


AB_BASHRC_BEFORE = """# Aliases
alias ls='ls --color=auto'
alias interactive='qrsh -g gcc50533 -l rt_G.small=1 -l h_rt=01:00:00'
alias interactive_full='qrsh -g gcc50533 -l rt_F=2 -l h_rt=01:00:00'
alias hosts='cat $SGE_JOB_HOSTLIST'
alias points='show_point'
alias usage='show_point | awk -v MAP=/home/aca10017by/scripts/user.dat -f /home/aca10017by/scripts/usage.awk'

# Modules
source /etc/profile.d/modules.sh
module load hpcx cuda cudnn nccl #intel-mkl intel


# >>> harness managed >>>
"""
AB_BASHRC_AFTER = """# Site aliases
alias points='show_point'
alias usage='show_point | awk -v MAP=/home/aca10017by/scripts/user.dat -f /home/aca10017by/scripts/usage.awk'

%s
# >>> harness managed >>>
""" % module_hook("ab")

AB2_BASHRC_BEFORE = """# Aliases
alias ls='ls --color=auto'
alias interactive='qrsh -g gcc50533 -l rt_G.small=1 -l h_rt=01:00:00'
alias interactive_full='qrsh -g gcc50533 -l rt_F=2 -l h_rt=01:00:00'
alias hosts='cat $SGE_JOB_HOSTLIST'
alias points='show_point'

# Modules
source /etc/profile.d/modules.sh
module load hpcx cuda cudnn nccl #intel-mkl intel


# >>> harness managed >>>
"""
AB2_BASHRC_AFTER = """# Site aliases
alias points='show_point'

%s
# >>> harness managed >>>
""" % module_hook("ab2")

AB_PROFILE_BEFORE = """# PyEnv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# SSH Agent
if [ -z "$SSH_AUTH_SOCK" ]; then
eval `ssh-agent -s` &>/dev/null
fi

# MPI (This causes the shell to pause)
#export MASTER_ADDR=`head -n 1 $SGE_JOB_HOSTLIST`

# >>> harness managed >>>
"""

AGENT_MPI_BEFORE = """# SSH Agent
if [ -z "$SSH_AUTH_SOCK" ]; then
eval `ssh-agent -s` &>/dev/null
fi

# MPI (This causes the shell to pause)
#export MASTER_ADDR=`head -n 1 $SGE_JOB_HOSTLIST`

# >>> harness managed >>>
"""

AL_BASHRC_BEFORE = """# Alias
alias ls='ls --color=auto'

# Start image
# harness: use prgenv for an interactive uenv

# >>> harness managed >>>
"""

AL_PROFILE_BEFORE = """# Local installs
export PATH=$HOME/.local/bin:$PATH
export CPATH=$HOME/.local/include:$CPATH
export LIBRARY_PATH=$HOME/.local/lib:$LIBRARY_PATH
export LD_LIBRARY_PATH=$HOME/.local/lib:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/.local/lib/pkgconfig

# Python
export UV_VENV_ROOT=$HOME/.venv
activate () {
  source $UV_VENV_ROOT/$1/bin/activate
}

# SSH Agent
if [ -z "$SSH_AUTH_SOCK" ]; then
  eval `ssh-agent -s` &>/dev/null
fi

# >>> harness managed >>>
"""

RC_BASHRC_BEFORE = """# User specific environment
if ! [[ "$PATH" =~ "$DATA/.local/bin:" ]]
then
    PATH="$DATA/.local/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
"""
RC_BASHRC_AFTER = """# Uncomment the following line if you don't like systemctl's auto-paging feature:
"""

RC_PROFILE_BEFORE = """# Local installs
export DATA=/lvs0/rccs-asfm/rio.yokota
export PATH=$DATA/.local/bin:$PATH
export CPATH=$DATA/.local/include:$CPATH
export LIBRARY_PATH=$DATA/.local/lib:$LIBRARY_PATH
export LD_LIBRARY_PATH=$DATA/.local/lib:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$DATA/.local/lib/pkgconfig

# PyEnv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# SSH Agent
if [ -z "$SSH_AUTH_SOCK" ]; then
  eval `ssh-agent -s` &>/dev/null
fi


# >>> harness managed >>>
"""

T4_BASHRC_BEFORE = """# PyTorch modules
module use /gs/fs/tga-NII-LLM/modules/modulefiles
module load ylab/cuda/12.8
module load ylab/cudnn/9.7.0
module load ylab/nccl/cuda-12.8/2.26.2
module load ylab/hpcx/2.21.0

# Alias
alias interactive="qrsh -g tga-bayes-crest -l node_f=1 -l h_rt=1:00:00"
alias points="t4-user-info group point"

# Bash completion
complete -W "\\`grep -oE '^[a-zA-Z0-9_.-]+:([^=]|$)' ?akefile | sed 's/[^a-zA-Z0-9_.-]*$//'\\`" make

# >>> harness managed >>>
"""
T4_BASHRC_AFTER = """# Site aliases
alias interactive="qrsh -g tga-bayes-crest -l node_f=1 -l h_rt=1:00:00"
alias points="t4-user-info group point"

%s
# >>> harness managed >>>
""" % module_hook("t4")

T4_PROFILE_BEFORE = """# Define $FS
export FS=/gs/bs/jh250019/yokota
#export FS=$HOME

# Local installs
export PATH=$FS/.local/bin:$PATH
export CPATH=$FS/.local/include:$CPATH
export LIBRARY_PATH=$FS/.local/lib:$LIBRARY_PATH
export LD_LIBRARY_PATH=$FS/.local/lib:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$FS/.local/lib/pkgconfig

# Python
export PYTHONUSERBASE=$FS/.local
export UV_CACHE_DIR=$FS/.cache/uv
export UV_VENV_ROOT=$FS/.venv
activate () {
  source $UV_VENV_ROOT/$1/bin/activate
}

# Matplotlib
export MPLBACKEND=Qt5Agg
export XDG_RUNTIME_DIR="/tmp/runtime-$USER"

# SSH Agent
if [ -z "$SSH_AUTH_SOCK" ]; then
  eval `ssh-agent -s` &>/dev/null
fi

# PyTorch Distributed
if [ -f "$PE_HOSTFILE" ]; then
  export MASTER_ADDR=`head -n 1 $PE_HOSTFILE | cut -d " " -f 1`
fi

# Huggingface cache
export HF_HOME=$FS/.cache

# Apptainer
export APPTAINER_TMPDIR=$T4TMPDIR/$USER/apptainer/tmp
export APPTAINER_CACHEDIR=$T4TMPDIR/$USER/apptainer/cache

# >>> harness managed >>>
"""

RI_GUARD_BEFORE = """# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
"""
RI_GUARD_AFTER = """# Keep non-interactive Bash silent while loading the managed base profile.
case $- in
    *i*) ;;
    *)
        if [ -r "$HOME/harness/shell/profile.sh" ]; then
            . "$HOME/harness/shell/profile.sh"
        fi
        return
        ;;
esac
"""
RI_HISTORY_BEFORE = """# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
"""
RI_HISTORY_AFTER = """# check the window size after each command and, if necessary,
"""
RI_PROMPT_BEFORE = """# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
\t# We have color support; assume it's compliant with Ecma-48
\t# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
\t# a case would tend to support setf rather than setaf.)
\tcolor_prompt=yes
    else
\tcolor_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\\[\\033[01;32m\\]\\u@\\h\\[\\033[00m\\]:\\[\\033[01;34m\\]\\w\\[\\033[00m\\]\\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\\u@\\h:\\w\\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\\[\\e]0;${debian_chroot:+($debian_chroot)}\\u@\\h: \\w\\a\\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
"""
RI_PROMPT_AFTER = """# enable color support of ls and also add handy aliases
"""
RI_DIRCOLORS_BEFORE = """if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
"""
RI_DIRCOLORS_AFTER = """if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi
"""
RI_TAIL_BEFORE = r"""# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
"""
RI_TAIL_AFTER = """# Site aliases
alias l='ls -CF'

# enable programmable completion features (you don't need to enable
"""


def rules_for(host, relpath, data):
    marker = "# >>> harness managed >>>\n"
    if host == "local" and relpath == ".bashrc":
        return list(LOCAL_RULES)
    if host == "ab" and relpath == ".bashrc":
        return [rule("ab-bashrc", AB_BASHRC_BEFORE, AB_BASHRC_AFTER)]
    if host == "ab" and relpath == ".bash_profile":
        return [rule("ab-profile", AB_PROFILE_BEFORE, marker)]
    if host == "ab2" and relpath == ".bashrc":
        return [rule("ab2-bashrc", AB2_BASHRC_BEFORE, AB2_BASHRC_AFTER)]
    if host == "ab2" and relpath == ".bash_profile":
        pattern = re.compile(b(r"# off +\n(?:# +\n){5}\n") +
                             re.escape(b(AGENT_MPI_BEFORE)))
        match = pattern.search(data)
        if match:
            return [{"name": "ab2-profile", "before": match.group(0), "after": b(marker)}]
        return []
    if host == "ri" and relpath == ".bashrc":
        return [
            rule("ri-noninteractive-guard", RI_GUARD_BEFORE, RI_GUARD_AFTER),
            rule("ri-history", RI_HISTORY_BEFORE, RI_HISTORY_AFTER),
            rule("ri-prompt", RI_PROMPT_BEFORE, RI_PROMPT_AFTER),
            rule("ri-dircolors", RI_DIRCOLORS_BEFORE, RI_DIRCOLORS_AFTER),
            rule("ri-alias-tail", RI_TAIL_BEFORE, RI_TAIL_AFTER),
        ]
    if host == "al" and relpath == ".bashrc":
        return [rule("al-bashrc", AL_BASHRC_BEFORE, marker)]
    if host == "al" and relpath == ".bash_profile":
        return [rule("al-profile", AL_PROFILE_BEFORE, marker)]
    if host == "rc" and relpath == ".bashrc":
        return [rule("rc-bashrc", RC_BASHRC_BEFORE, RC_BASHRC_AFTER)]
    if host == "rc" and relpath == ".bash_profile":
        return [rule("rc-profile", RC_PROFILE_BEFORE, marker)]
    if host == "t4" and relpath == ".bashrc":
        return [rule("t4-bashrc", T4_BASHRC_BEFORE, T4_BASHRC_AFTER)]
    if host == "t4" and relpath == ".bash_profile":
        return [rule("t4-profile", T4_PROFILE_BEFORE, marker)]
    return []


def target_paths(host, home):
    paths = [os.path.join(home, ".bashrc")]
    if host in ("ab", "ab2", "al", "rc", "t4"):
        paths.append(os.path.join(home, ".bash_profile"))
    if host == "local":
        paths.append(os.path.join(home, ".ssh", "config"))
    return paths


def strict_metadata(path, uid):
    try:
        info = os.lstat(path)
    except OSError as exc:
        raise Refusal("required path unavailable: %s" % path) from exc
    if not stat.S_ISREG(info.st_mode) or stat.S_ISLNK(info.st_mode):
        raise Refusal("path is not a strict regular file: %s" % path)
    if info.st_uid != uid or info.st_nlink != 1:
        raise Refusal("unsafe owner/link metadata: %s" % path)
    return info


def apply_rules(data, rules):
    current = data
    changed = []
    for item in rules:
        before = item["before"]
        count = current.count(before)
        if count > 1:
            raise Refusal("reviewed block is duplicated: %s" % item["name"])
        if count == 1:
            current = current.replace(before, item["after"], 1)
            changed.append(item)
    return current, changed


def validate_aliases(host, data):
    names = []
    for line in data.decode("utf-8").splitlines():
        found = re.match(r"^[ \t]*alias[ \t]+([A-Za-z_][A-Za-z0-9_]*)=", line)
        if found:
            names.append(found.group(1))
    expected = {
        "local": ["al"], "ab": ["points", "usage"], "ab2": ["points"],
        "ri": ["l"], "al": [], "rc": [], "t4": ["interactive", "points"],
    }[host]
    if names != expected or names != sorted(set(names)):
        raise Refusal("normalized alias set/order mismatch for %s" % host)


def validate_normalized(host, relpath, data):
    text = data.decode("utf-8")
    if text.count("# >>> harness early managed >>>") != 1:
        raise Refusal("early managed marker mismatch: %s" % relpath)
    if text.count("# >>> harness managed >>>") != 1:
        raise Refusal("managed marker mismatch: %s" % relpath)
    forbidden = [".bash_common"]
    if relpath == ".bashrc":
        validate_aliases(host, data)
        forbidden.extend(["alias a=", "alias ducks=", "alias grep=", "alias la=",
                          "alias ll=", "alias lla=", "alias ls=", "alias v="])
        if host in ("ab", "ab2", "t4"):
            # The readable-file guard and source command each name the helper.
            if text.count("shell/module-stack.sh") != 2:
                raise Refusal("module-stack hook mismatch for %s" % host)
        if host == "ri":
            forbidden.extend(["alias alert=", "alias egrep=", "alias fgrep=",
                              "HISTSIZE=1000", "color_prompt", "~/.bash_aliases"])
        if host == "rc":
            forbidden.extend(["$DATA/.local/bin"])
    else:
        forbidden.extend(["ssh-agent -s", "PYENV_ROOT", "pyenv init",
                          "UV_VENV_ROOT", "activate ()", "export FS=",
                          "export DATA=", "export CPATH=", "export LIBRARY_PATH=",
                          "export LD_LIBRARY_PATH=", "export PKG_CONFIG_PATH="])
        if host == "t4":
            forbidden.extend(["PYTHONUSERBASE", "MPLBACKEND", "XDG_RUNTIME_DIR",
                              "MASTER_ADDR", "APPTAINER_TMPDIR", "APPTAINER_CACHEDIR",
                              "export HF_HOME="])
    for token in forbidden:
        if token in text:
            raise Refusal("normalized file retains reviewed obsolete token")


def transform_ssh(data):
    lines = data.splitlines(True)
    records = []
    for hostname in SSH_FORWARD_HOSTS:
        header = b("Host %s\n" % hostname)
        indexes = [index for index, line in enumerate(lines) if line == header]
        if len(indexes) != 1:
            raise Refusal("SSH host stanza count mismatch: %s" % hostname)
        index = indexes[0]
        end = len(lines)
        for candidate in range(index + 1, len(lines)):
            if re.match(br"^[ \t]*(Host|Match)[ \t]+", lines[candidate], re.I):
                end = candidate
                break
        values = [line for line in lines[index + 1:end]
                  if re.match(br"^[ \t]*ForwardAgent[ \t]+", line, re.I)]
        if len(values) > 1:
            raise Refusal("duplicate ForwardAgent directive: %s" % hostname)
        if values:
            if values[0].strip().lower() != b"forwardagent yes":
                raise Refusal("conflicting ForwardAgent directive: %s" % hostname)
            continue
        inserted = b("    ForwardAgent yes\n")
        lines.insert(index + 1, inserted)
        records.append({"name": "ssh-forward-%s" % hostname,
                        "before": header, "after": header + inserted})
    return b("").join(lines), records


def validate_ssh(data):
    text = data.decode("utf-8")
    if text.lower().count("forwardagent yes") != len(SSH_FORWARD_HOSTS):
        raise Refusal("SSH forwarding directive count mismatch")
    if re.search(r"(?im)^\s*Host\s+\*\s*\n\s*ForwardAgent\s+yes\s*$", text):
        raise Refusal("ForwardAgent must not be enabled under Host *")


def write_all(fd, data):
    offset = 0
    while offset < len(data):
        written = os.write(fd, data[offset:])
        if written <= 0:
            raise OSError("short write")
        offset += written


def validate_candidate(path, data):
    directory = os.path.dirname(path)
    fd, candidate = tempfile.mkstemp(prefix=os.path.basename(path) + ".harness-startup.",
                                     dir=directory)
    try:
        write_all(fd, data)
        os.fsync(fd)
        os.close(fd)
        fd = -1
        if path.endswith("/.ssh/config"):
            for hostname in SSH_FORWARD_HOSTS:
                result = subprocess.call(["ssh", "-G", "-F", candidate, hostname],
                                         stdout=subprocess.DEVNULL,
                                         stderr=subprocess.DEVNULL)
                if result != 0:
                    raise Refusal("candidate SSH configuration rejected")
        else:
            if subprocess.call(["bash", "-n", candidate], stdout=subprocess.DEVNULL,
                               stderr=subprocess.DEVNULL) != 0:
                raise Refusal("candidate Bash syntax rejected: %s" % path)
    finally:
        if fd >= 0:
            os.close(fd)
        try:
            os.unlink(candidate)
        except OSError:
            pass


def atomic_replace(path, data, mode):
    directory = os.path.dirname(path)
    fd, candidate = tempfile.mkstemp(prefix=os.path.basename(path) + ".harness-startup.",
                                     dir=directory)
    try:
        write_all(fd, data)
        os.fsync(fd)
        os.fchmod(fd, mode)
        os.close(fd)
        fd = -1
        os.replace(candidate, path)
        candidate = None
    finally:
        if fd >= 0:
            os.close(fd)
        if candidate is not None:
            try:
                os.unlink(candidate)
            except OSError:
                pass


def encode_rule(item):
    return {"name": item["name"],
            "before": base64.b64encode(item["before"]).decode("ascii"),
            "after": base64.b64encode(item["after"]).decode("ascii")}


def decode_rule(item):
    return {"name": item["name"],
            "before": base64.b64decode(item["before"]),
            "after": base64.b64decode(item["after"])}


def write_manifest(path, manifest):
    directory = os.path.dirname(path)
    fd, temporary = tempfile.mkstemp(prefix=".startup-manifest.", dir=directory)
    try:
        os.fchmod(fd, 0o600)
        payload = (json.dumps(manifest, sort_keys=True, separators=(",", ":")) + "\n").encode("utf-8")
        write_all(fd, payload)
        os.fsync(fd)
        os.close(fd)
        fd = -1
        os.replace(temporary, path)
        temporary = None
    finally:
        if fd >= 0:
            os.close(fd)
        if temporary is not None:
            try:
                os.unlink(temporary)
            except OSError:
                pass


def require_clean_harness():
    output = subprocess.check_output(["git", "-C", ROOT, "status", "--porcelain"])
    if output:
        raise Refusal("startup apply requires clean harness")


def prepare(host, home):
    uid = os.getuid()
    prepared = []
    for path in target_paths(host, home):
        info = strict_metadata(path, uid)
        with open(path, "rb") as handle:
            data = handle.read()
        if path.endswith("/.ssh/config"):
            result, changed = transform_ssh(data)
            validate_ssh(result)
        else:
            relpath = os.path.basename(path)
            rules = rules_for(host, relpath, data)
            result, changed = apply_rules(data, rules)
            validate_normalized(host, relpath, result)
        validate_candidate(path, result)
        prepared.append({"path": path, "identity": [info.st_dev, info.st_ino, info.st_uid,
                                                       stat.S_IMODE(info.st_mode), info.st_nlink,
                                                       info.st_size],
                         "before": data, "after": result, "rules": changed})
    return prepared


def apply(host, home, prepared):
    changed = [item for item in prepared if item["rules"]]
    if not changed:
        print("END startup_normalize host=%s changes=none" % host)
        return
    state_root = os.path.join(home, ".local", "state", "harness", "transactions")
    os.makedirs(state_root, mode=0o700, exist_ok=True)
    os.chmod(os.path.dirname(state_root), 0o700)
    os.chmod(state_root, 0o700)
    transaction = datetime.datetime.now(datetime.timezone.utc).strftime(
        "%Y%m%dT%H%M%SZ") + "-%d-startup" % os.getpid()
    manifest_path = os.path.join(state_root, transaction + ".startup.json")
    manifest = {"schema": 1, "status": "pending", "host": host,
                "revision": subprocess.check_output(["git", "-C", ROOT, "rev-parse", "HEAD"]).decode().strip(),
                "applied": 0, "records": []}
    for item in changed:
        manifest["records"].append({"path": item["path"],
                                    "mode": item["identity"][3],
                                    "rules": [encode_rule(entry) for entry in item["rules"]]})
    write_manifest(manifest_path, manifest)
    completed = []
    try:
        for item in changed:
            observed = strict_metadata(item["path"], os.getuid())
            identity = [observed.st_dev, observed.st_ino, observed.st_uid,
                        stat.S_IMODE(observed.st_mode), observed.st_nlink, observed.st_size]
            if identity != item["identity"]:
                raise Refusal("destination metadata changed before apply")
            with open(item["path"], "rb") as handle:
                if handle.read() != item["before"]:
                    raise Refusal("destination bytes changed before apply")
            atomic_replace(item["path"], item["after"], item["identity"][3])
            completed.append(item)
            manifest["applied"] = len(completed)
            write_manifest(manifest_path, manifest)
        manifest["status"] = "complete"
        write_manifest(manifest_path, manifest)
    except Exception:
        for item in reversed(completed):
            try:
                with open(item["path"], "rb") as handle:
                    if handle.read() == item["after"]:
                        atomic_replace(item["path"], item["before"], item["identity"][3])
            except Exception:
                pass
        manifest["status"] = "failed"
        write_manifest(manifest_path, manifest)
        raise
    print("TRANSACTION id=%s status=complete files=%d" % (transaction, len(changed)))
    print("END startup_normalize host=%s changes=applied" % host)


def rollback(transaction, home):
    if not re.match(r"^[A-Za-z0-9._-]+$", transaction):
        raise Refusal("invalid transaction id")
    path = os.path.join(home, ".local", "state", "harness", "transactions",
                        transaction + ".startup.json")
    info = strict_metadata(path, os.getuid())
    if stat.S_IMODE(info.st_mode) != 0o600:
        raise Refusal("unsafe transaction manifest mode")
    with open(path, "r", encoding="utf-8") as handle:
        manifest = json.load(handle)
    if manifest.get("schema") != 1 or manifest.get("status") != "complete":
        raise Refusal("transaction is not complete")
    prepared = []
    for record in manifest["records"]:
        target = record["path"]
        target_info = strict_metadata(target, os.getuid())
        with open(target, "rb") as handle:
            current = handle.read()
        original = current
        rules = [decode_rule(item) for item in record["rules"]]
        for item in reversed(rules):
            if current.count(item["after"]) != 1:
                raise Refusal("rollback block changed: %s" % item["name"])
            current = current.replace(item["after"], item["before"], 1)
        validate_candidate(target, current)
        prepared.append({"path": target, "before": original, "after": current,
                         "mode": record["mode"], "identity": target_info})
    completed = []
    try:
        for item in prepared:
            with open(item["path"], "rb") as handle:
                if handle.read() != item["before"]:
                    raise Refusal("rollback destination changed")
            atomic_replace(item["path"], item["after"], item["mode"])
            completed.append(item)
    except Exception:
        for item in reversed(completed):
            try:
                with open(item["path"], "rb") as handle:
                    if handle.read() == item["after"]:
                        atomic_replace(item["path"], item["before"], item["mode"])
            except Exception:
                pass
        raise
    manifest["status"] = "rolled-back"
    write_manifest(path, manifest)
    print("TRANSACTION id=%s status=rolled-back files=%d" % (transaction, len(prepared)))


def main():
    parser = argparse.ArgumentParser(prog="harness startup-normalize")
    parser.add_argument("--host", choices=HOSTS)
    parser.add_argument("--plan", action="store_true")
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--rollback")
    args = parser.parse_args()
    selected = sum(bool(value) for value in (args.plan, args.apply, args.rollback))
    if selected != 1:
        parser.error("choose exactly one of --plan, --apply, or --rollback")
    home = os.path.expanduser("~")
    if args.rollback:
        rollback(args.rollback, home)
        return
    if not args.host:
        parser.error("--host is required for plan/apply")
    if args.apply:
        require_clean_harness()
    prepared = prepare(args.host, home)
    print("STARTUP_NORMALIZE_PLAN host=%s mode=%s contents=reviewed-public-blocks-only" %
          (args.host, "apply" if args.apply else "plan"))
    for item in prepared:
        label = os.path.relpath(item["path"], home)
        if item["rules"]:
            print("UPDATE file=%s rules=%d" % (label, len(item["rules"])))
        else:
            print("KEEP file=%s state=normalized" % label)
    if args.plan:
        print("END startup_normalize host=%s changes=not-applied" % args.host)
    else:
        apply(args.host, home, prepared)


if __name__ == "__main__":
    try:
        main()
    except Refusal as exc:
        print("harness: %s" % exc, file=sys.stderr)
        sys.exit(2)
