# Persistent session names in the status bar
set -g status-left-length 80
set -g status-left '#[bold]#{session_name} #[default]'

# Navigate sessions
bind-key N switch-client -n
bind-key P switch-client -p

# Browse the complete hierarchy
bind-key Space choose-tree -Zw
